[package]
name = "lit2png"
version = "0.1.0"
edition = "2021"
description = "Discord Times (2003) LIT/UGS/TGA graphics converter to PNG"
license = "MIT"

[dependencies]
image = { version = "0.25", default-features = false, features = ["png", "tga", "bmp"] }
thiserror = "1"
clap = { version = "4", features = ["derive"] }

[profile.release]
opt-level = 3

[lib]
name = "lit2png_lib"
path = "src/lib.rs"

[[bin]]
name = "lit2png"
path = "src/main.rs"
