[package]
name = "DT_Remastered"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
dyn-clone = "1.0.6"
derive_more = "0.99.16"
rand = "0.8.5"
