[package]
name = "rust_book_introduction"
version = "0.1.0"
edition = "2021"

[dependencies]
notan_ui = {path = "../.."}
notan = {git = "https://github.com/Nazariglez/notan.git", features=["text"]}
once_cell = "1.15.0"
math_thingies = "0.1.0"