[package]
name = "container_buttons"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
notan = {path = "../../../notan", features=["text"]}
notan_ui = {path = "../.."}
once_cell = "1.15.0"
